# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: playlist_editor_development

test:
  <<: *default
  database: playlist_editor_test

production:
  <<: *default
  database: playlist_editor_production
  username: ubuntu
  password: <%= ENV['DOJOSECRETS_DATABASE_PASSWORD'] %>
